In [1]:
from keras.preprocessing import sequence, text
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM
import pandas as pd
import numpy as np

#train_data_source = './exercise_data/human_dna_train_small.csv'
train_data_source = './exercise_data/human_dna_train_split_5_95.csv'
val_data_source = './exercise_data/human_dna_validation_split.csv'
test_data_source = './exercise_data/human_dna_test_split.csv'

train_df = pd.read_csv(train_data_source, header=0)
test_df = pd.read_csv(test_data_source, header=0)

train_seq = train_df['sequences']
train_label = train_df['labels']
test_seq = test_df['sequences']
test_label = test_df['labels']

# Preprocess
tk = text.Tokenizer(char_level=True)
tk.fit_on_texts(train_seq)

train_seq_tok = tk.texts_to_sequences(train_seq)
test_seq_tok = tk.texts_to_sequences(test_seq)

train_seq = np.array(train_seq)
train_seq_tok = np.array(train_seq_tok)
train_label = np.array(train_label)
test_seq = np.array(test_seq)
test_seq_tok = np.array(test_seq_tok)
test_label = np.array(test_label)

print('train_seq shape:', train_seq.shape)
print('test_seq shape:', test_seq.shape)

Using TensorFlow backend.


train_seq shape: (29420,)
test_seq shape: (33333,)


In [2]:
train_label[train_label<0]=0
test_label[test_label<0]=0

In [3]:
train_label

array([1, 1, 1, ..., 0, 0, 0])

In [4]:
train_seq_tok = train_seq_tok - np.ones(shape=train_seq_tok.shape)
test_seq_tok = test_seq_tok - np.ones(shape=test_seq_tok.shape)

In [5]:
train_seq_tok

array([[0., 3., 1., ..., 1., 0., 1.],
       [0., 2., 2., ..., 0., 0., 0.],
       [1., 2., 2., ..., 1., 2., 0.],
       ...,
       [2., 0., 0., ..., 1., 1., 2.],
       [1., 3., 1., ..., 2., 1., 1.],
       [2., 0., 0., ..., 1., 1., 1.]])

In [6]:
train_seq_tok_split = np.hsplit(train_seq_tok, 2)

In [7]:
train_seq_tok.shape

(29420, 398)

In [8]:
train_seq_tok_split[0].shape

(29420, 199)

In [9]:
train_seq_tok[0]

array([0., 3., 1., 1., 2., 1., 2., 2., 0., 0., 1., 1., 2., 3., 1., 1., 3.,
       0., 0., 2., 0., 2., 2., 1., 0., 2., 2., 0., 3., 1., 0., 2., 2., 1.,
       3., 2., 1., 0., 1., 2., 2., 2., 1., 1., 3., 0., 1., 0., 0., 2., 3.,
       1., 1., 1., 0., 0., 3., 0., 0., 2., 1., 2., 3., 1., 0., 2., 2., 0.,
       2., 0., 0., 2., 1., 3., 1., 2., 2., 2., 1., 1., 2., 1., 1., 1., 1.,
       3., 1., 2., 0., 1., 0., 0., 3., 3., 1., 2., 1., 0., 3., 1., 2., 0.,
       0., 1., 2., 0., 2., 0., 2., 2., 3., 1., 2., 0., 1., 1., 1., 1., 3.,
       1., 3., 1., 0., 2., 1., 2., 2., 2., 2., 0., 2., 1., 3., 0., 2., 1.,
       1., 2., 2., 2., 1., 1., 2., 3., 1., 2., 3., 1., 1., 1., 1., 1., 3.,
       0., 2., 2., 3., 1., 2., 1., 1., 1., 1., 1., 1., 3., 1., 1., 2., 3.,
       1., 2., 3., 0., 3., 0., 0., 0., 3., 0., 3., 0., 2., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 2., 3., 3., 1., 1., 1., 2., 2., 1., 0., 1., 3.,
       3., 0., 3., 3., 3., 0., 3., 1., 1., 3., 1., 1., 0., 2., 2., 2., 3.,
       1., 0., 0., 3., 3.

In [10]:
test_seq_tok_split = np.hsplit(test_seq_tok, 2)

In [11]:
train_seq_tok_split[0][0]

array([0., 3., 1., 1., 2., 1., 2., 2., 0., 0., 1., 1., 2., 3., 1., 1., 3.,
       0., 0., 2., 0., 2., 2., 1., 0., 2., 2., 0., 3., 1., 0., 2., 2., 1.,
       3., 2., 1., 0., 1., 2., 2., 2., 1., 1., 3., 0., 1., 0., 0., 2., 3.,
       1., 1., 1., 0., 0., 3., 0., 0., 2., 1., 2., 3., 1., 0., 2., 2., 0.,
       2., 0., 0., 2., 1., 3., 1., 2., 2., 2., 1., 1., 2., 1., 1., 1., 1.,
       3., 1., 2., 0., 1., 0., 0., 3., 3., 1., 2., 1., 0., 3., 1., 2., 0.,
       0., 1., 2., 0., 2., 0., 2., 2., 3., 1., 2., 0., 1., 1., 1., 1., 3.,
       1., 3., 1., 0., 2., 1., 2., 2., 2., 2., 0., 2., 1., 3., 0., 2., 1.,
       1., 2., 2., 2., 1., 1., 2., 3., 1., 2., 3., 1., 1., 1., 1., 1., 3.,
       0., 2., 2., 3., 1., 2., 1., 1., 1., 1., 1., 1., 3., 1., 1., 2., 3.,
       1., 2., 3., 0., 3., 0., 0., 0., 3., 0., 3., 0., 2., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 2., 3., 3., 1., 1., 1., 2.])

In [12]:
from keras.layers import Dropout, concatenate, Input
import keras as K

# def recall_m(y_true, y_pred):
#     true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
#     possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
#     recall = true_positives / (possible_positives + K.epsilon())
#     return recall

# def precision_m(y_true, y_pred):
#     true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
#     predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
#     precision = true_positives / (predicted_positives + K.epsilon())
#     return precision

# def f1_m(y_true, y_pred):
#     precision = precision_m(y_true, y_pred)
#     recall = recall_m(y_true, y_pred)
#     return 2*((precision*recall)/(precision+recall+K.epsilon()))

# max_features = 20000
batch_size = 32
epochs = 100
learning_rate = 0.001


# First Half
first_half = Input(shape=(199,))
x = Dense(150, activation='relu')(first_half)
x = Dropout(0.2)(x)
x = Dense(100, activation='relu')(x)
x = Dropout(0.2)(x)
x = Dense(75, activation='relu')(x)
x = Dropout(0.2)(x)
x = Dense(50, activation='relu')(x)
out_first = Dropout(0.2)(x)

second_half = Input(shape=(199,))
x = Dense(100, activation='relu')(second_half)
x = Dropout(0.2)(x)
x = Dense(50, activation='relu')(x)
x = Dropout(0.2)(x)
x = Dense(25, activation='relu')(x)
# x = Dropout(0.2)(x)
# x = Dense(50, activation='relu', input_shape=(75,))(x)
out_second = Dropout(0.2)(x)

concatenated = concatenate([out_first, out_second])
x = Dense(75, activation='relu')(concatenated)
# model.add(Dropout(0.2))
x = Dense(50, activation='relu')(x)
# model.add(Dropout(0.2))
x = Dense(20, activation='relu')(x)
# model.add(Dropout(0.2))
out_final = Dense(1, activation='sigmoid')(x)

model = K.Model([first_half, second_half], out_final)

# try using different optimizers and different optimizer configs
opt = K.optimizers.Adam(learning_rate=learning_rate)
model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['acc'])

# model.add(Dense(150, activation='relu', input_shape=(198,)))
# model.add(Dropout(0.2))
# model.add(Dense(100, activation='relu'))
# model.add(Dropout(0.2))
# model.add(Dense(75, activation='relu'))
# model.add(Dropout(0.2))
# out_a = model.add(Dense(50, activation='relu'))

# # Second Half
# model.add(Dense(150, activation='relu', input_shape=(198,)))
# model.add(Dropout(0.2))
# model.add(Dense(100, activation='relu'))
# model.add(Dropout(0.2))
# model.add(Dense(75, activation='relu'))
# model.add(Dropout(0.2))
# out_b = model.add(Dense(50, activation='relu'))

# # Concatenate
# concatenated = concatenate([out_a, out_b])
# model.add(Dense(100, activation='relu')(concatenated))
# # model.add(Dropout(0.2))
# model.add(Dense(50, activation='relu'))
# # model.add(Dropout(0.2))
# model.add(Dense(20, activation='relu'))
# # model.add(Dropout(0.2))
# model.add(Dense(1, activation='sigmoid'))

# # try using different optimizers and different optimizer configs
# opt = K.optimizers.Adam(learning_rate=learning_rate)
# model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['acc'])

print('Train...')
model.fit(train_seq_tok_split, train_label, batch_size=batch_size, epochs=epochs, validation_data=(test_seq_tok_split, test_label), class_weight={0: 0.5, 1: 0.95})
score, acc = model.evaluate(test_seq_tok_split, test_label, batch_size=batch_size)
print('Test score:', score)
print('Test accuracy:', acc)

Train...
Train on 29420 samples, validate on 33333 samples
Epoch 1/100
29420/29420 [==============================] - 7s 221us/step - loss: 0.1701 - acc: 0.9490 - val_loss: 0.2090 - val_acc: 0.9969
Epoch 2/100
29420/29420 [==============================] - 6s 205us/step - loss: 0.1584 - acc: 0.9500 - val_loss: 0.0812 - val_acc: 0.9969
Epoch 3/100
29420/29420 [==============================] - 6s 210us/step - loss: 0.1528 - acc: 0.9500 - val_loss: 0.0819 - val_acc: 0.9969
Epoch 4/100
29420/29420 [==============================] - 6s 208us/step - loss: 0.1485 - acc: 0.9500 - val_loss: 0.0824 - val_acc: 0.9969
Epoch 5/100
29420/29420 [==============================] - 6s 210us/step - loss: 0.1446 - acc: 0.9499 - val_loss: 0.0883 - val_acc: 0.9969
Epoch 6/100
29420/29420 [==============================] - 6s 207us/step - loss: 0.1409 - acc: 0.9500 - val_loss: 0.1795 - val_acc: 0.9965
Epoch 7/100
29420/29420 [==============================] - 6s 208us/step - loss: 0.1377 - acc: 0.9491 - val

29420/29420 [==============================] - 6s 206us/step - loss: 0.0238 - acc: 0.9868 - val_loss: 0.0788 - val_acc: 0.9774
Epoch 60/100
29420/29420 [==============================] - 6s 205us/step - loss: 0.0217 - acc: 0.9888 - val_loss: 0.0592 - val_acc: 0.9846
Epoch 61/100
29420/29420 [==============================] - 6s 202us/step - loss: 0.0216 - acc: 0.9878 - val_loss: 0.0953 - val_acc: 0.9739
Epoch 62/100
29420/29420 [==============================] - 6s 201us/step - loss: 0.0249 - acc: 0.9870 - val_loss: 0.0564 - val_acc: 0.9849
Epoch 63/100
29420/29420 [==============================] - 6s 201us/step - loss: 0.0216 - acc: 0.9878 - val_loss: 0.0619 - val_acc: 0.9851
Epoch 64/100
29420/29420 [==============================] - 6s 202us/step - loss: 0.0229 - acc: 0.9874 - val_loss: 0.0550 - val_acc: 0.9859
Epoch 65/100
29420/29420 [==============================] - 6s 198us/step - loss: 0.0237 - acc: 0.9869 - val_loss: 0.0562 - val_acc: 0.9838
Epoch 66/100
29420/29420 [=======