In [3]:
from keras.preprocessing import sequence, text
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM
import pandas as pd
import numpy as np

#train_data_source = './exercise_data/human_dna_train_small.csv'
train_data_source = './exercise_data/human_dna_train_split_5_95.csv'
val_data_source = './exercise_data/human_dna_validation_split.csv'
test_data_source = './exercise_data/human_dna_test_split.csv'

train_df = pd.read_csv(train_data_source, header=0)
test_df = pd.read_csv(test_data_source, header=0)

train_seq = train_df['sequences']
train_label = train_df['labels']
test_seq = test_df['sequences']
test_label = test_df['labels']

# Preprocess
tk = text.Tokenizer(char_level=True)
tk.fit_on_texts(train_seq)

train_seq_tok = tk.texts_to_sequences(train_seq)
test_seq_tok = tk.texts_to_sequences(test_seq)

train_seq = np.array(train_seq)
train_seq_tok = np.array(train_seq_tok)
train_label = np.array(train_label)
test_seq = np.array(test_seq)
test_seq_tok = np.array(test_seq_tok)
test_label = np.array(test_label)

print('train_seq shape:', train_seq.shape)
print('test_seq shape:', test_seq.shape)

train_seq shape: (29420,)
test_seq shape: (33333,)


In [4]:
train_label[train_label<0]=0
test_label[test_label<0]=0

In [5]:
train_label

array([1, 1, 1, ..., 0, 0, 0])

In [6]:
train_seq_tok = train_seq_tok - np.ones(shape=train_seq_tok.shape)
test_seq_tok = test_seq_tok - np.ones(shape=test_seq_tok.shape)

In [7]:
train_seq_tok

array([[0., 3., 1., ..., 1., 0., 1.],
       [0., 2., 2., ..., 0., 0., 0.],
       [1., 2., 2., ..., 1., 2., 0.],
       ...,
       [2., 0., 0., ..., 1., 1., 2.],
       [1., 3., 1., ..., 2., 1., 1.],
       [2., 0., 0., ..., 1., 1., 1.]])

In [8]:
train_seq_tok_split = np.hsplit(train_seq_tok, 2)

In [9]:
train_seq_tok.shape

(29420, 398)

In [10]:
train_seq_tok_split[0].shape

(29420, 199)

In [11]:
train_seq_tok[0]

array([0., 3., 1., 1., 2., 1., 2., 2., 0., 0., 1., 1., 2., 3., 1., 1., 3.,
       0., 0., 2., 0., 2., 2., 1., 0., 2., 2., 0., 3., 1., 0., 2., 2., 1.,
       3., 2., 1., 0., 1., 2., 2., 2., 1., 1., 3., 0., 1., 0., 0., 2., 3.,
       1., 1., 1., 0., 0., 3., 0., 0., 2., 1., 2., 3., 1., 0., 2., 2., 0.,
       2., 0., 0., 2., 1., 3., 1., 2., 2., 2., 1., 1., 2., 1., 1., 1., 1.,
       3., 1., 2., 0., 1., 0., 0., 3., 3., 1., 2., 1., 0., 3., 1., 2., 0.,
       0., 1., 2., 0., 2., 0., 2., 2., 3., 1., 2., 0., 1., 1., 1., 1., 3.,
       1., 3., 1., 0., 2., 1., 2., 2., 2., 2., 0., 2., 1., 3., 0., 2., 1.,
       1., 2., 2., 2., 1., 1., 2., 3., 1., 2., 3., 1., 1., 1., 1., 1., 3.,
       0., 2., 2., 3., 1., 2., 1., 1., 1., 1., 1., 1., 3., 1., 1., 2., 3.,
       1., 2., 3., 0., 3., 0., 0., 0., 3., 0., 3., 0., 2., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 2., 3., 3., 1., 1., 1., 2., 2., 1., 0., 1., 3.,
       3., 0., 3., 3., 3., 0., 3., 1., 1., 3., 1., 1., 0., 2., 2., 2., 3.,
       1., 0., 0., 3., 3.

In [12]:
test_seq_tok_split = np.hsplit(test_seq_tok, 2)

In [13]:
train_seq_tok_split[0][0]

array([0., 3., 1., 1., 2., 1., 2., 2., 0., 0., 1., 1., 2., 3., 1., 1., 3.,
       0., 0., 2., 0., 2., 2., 1., 0., 2., 2., 0., 3., 1., 0., 2., 2., 1.,
       3., 2., 1., 0., 1., 2., 2., 2., 1., 1., 3., 0., 1., 0., 0., 2., 3.,
       1., 1., 1., 0., 0., 3., 0., 0., 2., 1., 2., 3., 1., 0., 2., 2., 0.,
       2., 0., 0., 2., 1., 3., 1., 2., 2., 2., 1., 1., 2., 1., 1., 1., 1.,
       3., 1., 2., 0., 1., 0., 0., 3., 3., 1., 2., 1., 0., 3., 1., 2., 0.,
       0., 1., 2., 0., 2., 0., 2., 2., 3., 1., 2., 0., 1., 1., 1., 1., 3.,
       1., 3., 1., 0., 2., 1., 2., 2., 2., 2., 0., 2., 1., 3., 0., 2., 1.,
       1., 2., 2., 2., 1., 1., 2., 3., 1., 2., 3., 1., 1., 1., 1., 1., 3.,
       0., 2., 2., 3., 1., 2., 1., 1., 1., 1., 1., 1., 3., 1., 1., 2., 3.,
       1., 2., 3., 0., 3., 0., 0., 0., 3., 0., 3., 0., 2., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 2., 3., 3., 1., 1., 1., 2.])

In [25]:
train_seq_tok.shape
train_seq_tok_reshape = np.expand_dims(train_seq_tok, axis=0)
test_seq_tok_reshape = np.expand_dims(test_seq_tok, axis=0)
train_seq_tok_reshape.shape

(1, 29420, 398)

In [26]:
from keras.layers import Dropout, concatenate, Input, Conv1D, GlobalMaxPooling1D, Activation
import keras as K

# def recall_m(y_true, y_pred):
#     true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
#     possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
#     recall = true_positives / (possible_positives + K.epsilon())
#     return recall

# def precision_m(y_true, y_pred):
#     true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
#     predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
#     precision = true_positives / (predicted_positives + K.epsilon())
#     return precision

# def f1_m(y_true, y_pred):
#     precision = precision_m(y_true, y_pred)
#     recall = recall_m(y_true, y_pred)
#     return 2*((precision*recall)/(precision+recall+K.epsilon()))

# max_features = 20000
batch_size = 32
epochs = 100
learning_rate = 0.001
filters = 250
kernel_size = 3
hidden_dims = 250

model = Sequential()
model.add(Conv1D(filters,kernel_size,padding='valid',activation='relu',strides=1))
# model.add(GlobalMaxPooling1D())
# model.add(Dense(hidden_dims))
# model.add(Dropout(0.2))
# model.add(Activation('relu'))

# We project onto a single unit output layer, and squash it with a sigmoid:
# model.add(Dense(1))
# model.add(Activation('sigmoid'))


model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

print('Train...')
model.fit(train_seq_tok_reshape, train_label, batch_size=batch_size, epochs=epochs, validation_data=(test_seq_tok_reshape, test_label))
score, acc = model.evaluate(test_seq_tok_reshape, test_label, batch_size=batch_size)
print('Test score:', score)
print('Test accuracy:', acc)

Train...


ValueError: Error when checking target: expected conv1d_9 to have 3 dimensions, but got array with shape (29420, 1)